services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    restart: always
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python main.py"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    restart: always

volumes:
  postgres_:
