services:
  pgadmin:
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: "mental@mental.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: mental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
  pgadmin:
  